# Project Information
site_name: 'Animius Docs'
site_description: 'A Documentation of Animius'
site_author: 'gundamMC'
site_url: 'https://gundammc.github.io/Animius'

# Copyright
copyright: 'Copyright &copy; 2019 gundamMC'

# Navigation
nav:
    - Home: 'index.md'
    - About: 'about.md'
    - Commands:
        - Overview: 'commands/overview.md'
        - Quick Start: 'commands/quick_start.md'
        - Waifu: 'commands/waifu.md'
        - Model: 'commands/model.md'
        - Model Config: 'commands/model config.md'
        - Data: 'commands/data.md'
        - Embedding: 'commands/embedding.md'
        - Server: 'commands/server.md'
        - Console: 'commands/console.md'
    - File Structure:
        - Overview: 'file structure/overview.md'
    - Network: 
        - Overview: 'network/overview.md'
        - Authentication: 'network/authentication.md'
        - Encryption: 'network/encryption.md'

# Themes
theme:
    name: 'material'
    palette:
        primary: 'blue'
        accent: 'blue'

# Repo information
repo_name: 'gundamMC/Animius'
repo_url: 'https://github.com/gundamMC/Animius'

# Extensions
markdown_extensions:
  - codehilite:
      linenums: true
  - pymdownx.tilde
  - pymdownx.inlinehilite

# Social links
extra:
  social:
    - type: 'github'
      link: 'https://github.com/gundamMC'