site_name: 'Project Waifu Docs'
site_url: 'https://gundammc.github.io/Project-Waifu'
nav:
    - Home: 'index.md'
    - About: 'about.md'
    - Network: 
        - Overview: 'network/overview.md'
        - Authentication: 'network/authentication.md'
theme: 'material'
markdown_extensions:
  - codehilite:
      linenums: true
  - pymdownx.tilde
  - pymdownx.inlinehilite
