# Project Information
site_name: 'Animius Documentation'
site_description: 'A Documentation of Animius'
site_author: 'gundamMC'
site_url: 'https://gundammc.github.io/animius'

# Copyright
copyright: 'Copyright &copy; 2019 gundamMC'

# Navigation
nav:
    - Home: 'index.md'
    - Quick Start:
        - Overview: 'quick start/overview.md'
        - Python Library: 'quick start/python.md'
        - Commands: 'quick start/commands.md'
    - Python API:
        - am: 'python/am.md'
        - am.Chatbot: 'python/am.Chatbot.md'
        - am.IntentNER: 'python/am.IntentNER.md'
        - am.SpeakerVerification: 'python/am.SpeakerVerification.md'
        - am.Utils: 'python/am.Utils.md'
    - Commands:
        - Overview: 'commands/overview.md'
        - Waifu: 'commands/waifu.md'
        - Model: 'commands/model.md'
        - Model Config: 'commands/model config.md'
        - Data: 'commands/data.md'
        - Embedding: 'commands/embedding.md'
        - Server: 'commands/server.md'
        - Console: 'commands/console.md'
    - File Structure:
        - Overview: 'file_structure/overview.md'
    - Network: 
        - Overview: 'network/overview.md'
        - Authentication: 'network/authentication.md'
        - Encryption: 'network/encryption.md'
    - Animius Main Site: https://www.animius.org/

# Themes
theme:
    name: 'material'
    palette:
        primary: 'blue'
        accent: 'blue'

# Repo information
repo_name: 'Github'
repo_url: 'https://github.com/gundamMC/animius'

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      linenums: true
  - pymdownx.tilde
  - pymdownx.inlinehilite

# Social links
extra:
  social:
    - type: 'github'
      link: 'https://github.com/gundamMC'
