import animius.Chatbot as Chatbot
import animius.IntentNER as IntentNER
import animius.SpeakerVerification as SpeakerVerification
import animius.Utils as Utils
from animius.Model import Model
from animius.ModelConfig import *
from animius.ModelData import *
from animius.Waifu import Waifu
from animius.WordEmbedding import WordEmbedding
